-- DDL(Data Defiition Lang) "Tables and Columns"--Create--alter--Drop
-- DML(Data Manipulation Lang) "Rows and Data"--Insert--Delete--Update

----------------------------------- Create Table
Create Table Students (
RollNo int Primary Key not null auto increment,
StudentName Varchar(50),
PhoneNumber Bigint,--Holds Bigger Integers
Course varchar(50))
--Primary key here is used for Avoiding Duplicate Values And Null Values on a particular column
--Identity Is Used for Auto Generate Values for particular column 
--------------------------------------Inserting without Mentioning column names
Insert into Students values ('Mounika',7989878998,'Java')
Insert into Students values ('Deepak',7989878998,'Python')
Insert into Students values ('Shashank',7989878998,'Oracle')
Insert into Students values ('Manish',7989878998,'SQL')
Insert into Students values ('Sateesh',7989878998,'Cloud')
------------------------------------------------------------Inserting With Column Names(Preffered)
Insert Into Students (StudentName,PhoneNumber) Values ('Ashwin',8989756988,'C++') --Not Mentioning RollNo Because Its Auto Generated By Identity
-------------------------------------------------------Deleting using where clause
Delete From Students where RollNo = 1--Deleting using rollno (Preffered) 
Delete From Students where StudentName = 'Mounika'--Deleting using name
-------------------------Update
Update Students Set StudentName = 'Ramya' where RollNo = 1--Updating one row one column
Update Students Set StudentName = 'Ramya',PhoneNumber = 9897458997, Course = 'Devops' where RollNo  = 1--Updating multiple columns for one row
Update Students set Course = 'Devops'where RollNo in (1,2,3)--Updating One column for multiple records

----------------------------------------------------------------Alter 

Alter Table Students Add Salary int--Adding new column called Salary with INT datatype
Alter Table Students Alter Column Salary varchar(50)--Modifying datatype INT to Varchar
Alter Table Students Drop Column Salary--Deleting column Name Called 'Salary'
--------------------------------------------------------------------Drop Table
Drop Table Students--TO Delete the whole table

--Operators
--Mathematical Operators -- +,-,*,/
--Relational Operators >,<,>=,<=,=,<>,!=
--Logical Operators And/Or/NOT
Select * from MOCK_DATA where id = 5
Select * from MOCK_DATA where id < 10
Select * from MOCK_DATA where id <= 10
Select * from MOCK_DATA where id > 10
Select * from MOCK_DATA where id >= 10
Select * from MOCK_DATA where id <> 10

------------------------------------And/Or/Not
Select * from MOCK_DATA Where Id < 500 And Gender = 'Male'
Select * from MOCK_DATA Where Id > 5000 And Gender = 'Male'
Select * from MOCK_DATA where Id < 600 and Id > 300  
Select * from Mock_data where Id > 600 and Id < 300


------------Or Operator
Select * from MOCK_DATA Where Id > 5000 Or Gender = 'Male'
Select * from Mock_data where Id > 600 or Id < 300
------------------------------Between Operator
Select * from Mock_data where Id Between 300 and 600
Select * from Mock_data where Id Not Between 300 and 600
-----------------------------------IN Operator
Select * from Mock_Data where ID in (22,44,66,769,999)
Select * from MOCK_DATA where First_Name in ('Marcos',
'Moria',
'Dyann',
'Flory',
'Kathryn')
-----------------------------------------------Like Operator
Select * from MOCK_DATA Where First_Name Like 'A%'
Select * from MOCK_DATA Where First_Name Like '%A'
Select * from MOCK_DATA Where First_Name Like '%A%'
Select * from MOCK_DATA Where First_Name Like '%CA%'
Select * from MOCK_DATA Where First_Name Like '%C%A%'
Select * from MOCK_DATA Where First_Name Like '__A%'
----------------------------------------------
Select * from Student_Marks

----------Aggregate Functions
--Sum()
--Max()
--Min()
--Avg()
--Count()
Select Count(Score) From Student_Marks
--Today's Agenda
--What is Constraints
--Types of Constraints
--Create Table Command
--Dropping Constraints
--Naming Constraints
--Alter Table Command 

----Constraints are set of Restrictions you put on certain Column names
----To avoid Null Or Duplicate Values
----Keep My Table Clean And Accurate


--Primary Key -- It doesnt allow duplicates and null values --It can be used only once in one table 
--Not Null --It doesnt allow nulls 
--Unique key -- It doesnt allow duplicates 
--Foreign key -- It Helps To Create a connection with two or more tables 
--Check Constraint--It checks the given condition



Create Table Customers_Constraints
(
Customer_Id int Primary Key  ,--Constraint)
CustomerName Varchar(40) Not Null,
PhoneNumber Bigint Unique Not Null,
Age int Check (Age>=18)
)
Create Table Customers_Constraints
(
Customer_Id int ,--Constraint)
CustomerName Varchar(40) Not Null,
PhoneNumber Bigint Not Null,
Age int,
Constraint PK_Customers_CustomerID Primary Key(Customer_ID),
Constraint UQ_Customers_PhoneNumber  Unique(PhoneNumber),
Constraint CK_Customers_Age Check(Age>=18)
)




Drop Table Customers_Constraints
Select * from Customers_Constraints
Insert into Customers_Constraints Values (1,'Vamshi',9898992456,19)--Inserting Valid Record
Insert into Customers_Constraints (Customer_Id,PhoneNumber,Age)Values (2,9856598556,19)--Not Inserting Name 
Insert into Customers_Constraints(Customer_Id,CustomerName,PhoneNumber,Age)Values (2,'Arun',9856598556,19)-- Inserting Name 
Insert into Customers_Constraints Values (6,'Vamshi',989598556,16)--Inserting with age less than 18
Insert into Customers_Constraints Values (5,'Vamshi',9898992456,19)--Inserting Already Existing PhoneNumber
Delete from Customers_Constraints where Customer_Id = 1
------------------------------------------------------------------------------------
--Dropping Constraints



Alter Table Customers_Constraints Drop Constraint UQ_Customers_PhoneNumber
Alter Table Customers_Constraints Drop Constraint CK_Customers_Age
Alter Table Customers_Constraints Drop Constraint PK_Customers_CustomerID

--------------------------------------------------------------------------------
Update Customers_Constraints Set Age = 16 where age = 19

---------------------------------------------------------------------------------
--Adding Constraints Using Alter

ALter Table Customers_Constraints ADD COnstraint CK_Customers_Age Check (Age >= 18)
ALter Table Customers_Constraints ADD COnstraint PK_Customers_CustomerID Primary Key(Customer_ID)
ALter Table Customers_Constraints ADD COnstraint UK_Customers_PhoneNumber Unique(PhoneNumber)

---------------








